### PR TITLE
completes html-skeleton

### PR DESCRIPTION
**Pull request by aklepper20**
html-skeleton | Klepper

image

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Aly! Please complete this again not using the keyboard shortcut to create the HTML skeleton. I am testing your ability to write the code yourself, not use keyboard shortcuts 😉

Also, in the future, you want to take a screenshot of the output in the browser when you open the file, not the code. I can see the code here in your pull request 👍

**Review by codingcodymiller — COMMENTED** [review]
Hey Aly! In the future, make sure you wait to merge until after I have approved the exercise, that way i can give you feedback on your code 🤓

**Comment by thebearingedge** [comment]
@aklepper20 Please check out this branch, make a small change, commit, push, and open a new Pull Request so that @codingcodymiller can mark it as completed.

**Comment by aklepper20** [comment]
image

**Pull request merged**
